<!DOCTYPE html>
<html>
<head>
	<title>Promise</title>
	<link rel="stylesheet" type="text/css" href="../../css/main.css">
	<script type="text/javascript" src="../../js/jquery-1.9.12.js"></script>
	<meta charset="utf-8">
</head>
<body>
<div class="home"><a href="../../index.html">首页</a></div>

<div class="aTitle">基本用法</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
Promise 对象用于一个异步操作的最终完成（或失败）及其结果值的表示。
(简单点说就是处理异步请求。)

<b>语法：</b>
new Promise(
    /* executor */
    function(resolve, reject) {...}
);

<b>参数:</b>
executor
executor是一个带有 resolve 和 reject 两个参数的函数 。
executor 函数在Promise构造函数执行时同步执行
（executor 函数在Promise构造函数返回新建对象前被调用）。

<b>示例：</b>
// 模拟返回结果
const RESULT_SUCCESS = 'success';
const RESULT_FAILED = 'failed';
const RESULT_ERROR = 'error';
var flag = RESULT_FAILED;

doSomething()
	.then(
		function(result){
			console.log('成功', result);
		},
		function(result){
			console.log('失败', result);
		}
	)
	.catch(
		function (error){
			console.log('异常：', error);
		}
	)

function doSomething(){
	return new Promise(function(reselve, reject){
		// 异步操作获得结果，这里模拟
		if(flag === RESULT_ERROR){
			throw new Error("网络异常")
		}else{
			var isSuccess = flag===RESULT_SUCCESS;
			var result = {isSuccess, someInfo:{}};
		}
		
		if(result.isSuccess){
			reselve(result);
		}else{
			reject(result);
		}
	})
}


		</pre>
	</div>
	<div class="aShow" id="showResult1">
		
	</div>
</div>
<script>
$(function(){

// 模拟返回结果
const RESULT_SUCCESS = 'success';
const RESULT_FAILED = 'failed';
const RESULT_ERROR = 'error';
var flag = RESULT_SUCCESS;

doSomething()
	.then(
		function(result){
			$('#showResult1').html('成功');
			//console.log('成功:', result);
		},
		function(result){
			$('#showResult1').html('失败');
			//console.log('失败:', result);
		}
	)
	.catch(
		function (error){
			$('#showResult1').html('异常');
			//console.log('异常：', error);
		}
	)

function doSomething(){
	return new Promise(function(reselve, reject){
		// 异步操作获得结果，这里模拟
		if(flag === RESULT_ERROR){
			throw new Error("网络异常")
		}else{
			var isSuccess = flag===RESULT_SUCCESS;
			var result = {isSuccess, someInfo:{}};
		}
		
		if(result.isSuccess){
			reselve(result);
		}else{
			reject(result);
		}
	})
}

})
</script>


<div class="aTitle">链式调用</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
var begin = Date.now();
doStep1()
	.then( () => doStep2() )
	.then( () => doStep3() )
	.then( () => {
		var end = Date.now();
		console.log(`三个任务全部完成，耗时：${ end-begin } 毫秒`)
	})

function doStep1(){
	return new Promise( (resolve, reject) => {
		setTimeout(resolve, 1000)
	})
}
function doStep2(){
	return new Promise( (resolve, reject) => {
		setTimeout(resolve, 1000)
	})
}
function doStep3(){
	return new Promise( (resolve, reject) => {
		setTimeout(resolve, 1000)
	})
}

		</pre>
	</div>
	<div class="aShow" id="showResult2">
		
	</div>
</div>
<script>
$(function(){
	var begin = Date.now();
	doStep1()
	.then( () => doStep2() )
	.then( () => doStep3() )
	.then( () => {
		var end = Date.now();
		$('#showResult2').html(`三个任务全部完成，耗时：${ end-begin } 毫秒`)
	});


	function doStep1(){
		return new Promise( (resolve, reject) => {
			setTimeout(resolve, 1000)
		})
	}
	function doStep2(){
		return new Promise( (resolve, reject) => {
			setTimeout(resolve, 1000)
		})
	}
	function doStep3(){
		return new Promise( (resolve, reject) => {
			setTimeout(resolve, 1000)
		})
	}
})
</script>


<div class="aTitle">每步异常捕获</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
当某一步捕获异常后，后续步骤继续执行。
<b>脚本：</b>
var begin = Date.now();

doStep1()
.catch( () => {
	var end = Date.now();
	console.log(`第一步异常！！！ (${end-begin}毫秒)`)
})
.then( () => {
	var end = Date.now();
	console.log(`完成第一步 (${end-begin}毫秒)`)
	return doStep2()
} )
.catch( () => {
	var end = Date.now();
	console.log(`第二步异常！！！ (${end-begin}毫秒)`)
})
.then( () => {
	var end = Date.now();
	console.log(`完成第二步 (${end-begin}毫秒)`)
	return doStep3()
}  )
.catch( () => {
	var end = Date.now();
	console.log(`第三步异常！！！ (${end-begin}毫秒)`)
})
.then( () => {
	var end = Date.now();
	console.log(`结束 (${ end-begin } 毫秒)`)
});

function doStep1(){
	return new Promise( (resolve, reject) => {
		console.log('执行第一步')
		throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
function doStep2(){
	return new Promise( (resolve, reject) => {
		console.log('执行第二步')
		// throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
function doStep3(){
	return new Promise( (resolve, reject) => {
		console.log('执行第三步')
		// throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
		</pre>
	</div>
	<div class="aShow" id="showResult3">
		
	</div>
</div>
<script>
$(function(){

	var begin = Date.now();

	doStep1()
	.catch( () => {
		var end = Date.now();
		show(`第一步异常！！！ (${end-begin}毫秒)`)
	})
	.then( () => {
		var end = Date.now();
		show(`完成第一步 (${end-begin}毫秒)`)
		return doStep2()
	} )
	.catch( () => {
		var end = Date.now();
		show(`第二步异常！！！ (${end-begin}毫秒)`)
	})
	.then( () => {
		var end = Date.now();
		show(`完成第二步 (${end-begin}毫秒)`)
		return doStep3()
	}  )
	.catch( () => {
		var end = Date.now();
		show(`第三步异常！！！ (${end-begin}毫秒)`)
	})
	.then( () => {
		var end = Date.now();
		show(`结束 (${ end-begin } 毫秒)`)
	});

	function doStep1(){
		return new Promise( (resolve, reject) => {
			show('执行第一步')
			throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}
	function doStep2(){
		return new Promise( (resolve, reject) => {
			show('执行第二步')
			// throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}
	function doStep3(){
		return new Promise( (resolve, reject) => {
			show('执行第三步')
			// throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}

	function show(str){
		$('<p>'+str+'</p>').appendTo('#showResult3');
	}
})
</script>


<div class="aTitle">最后异常捕获</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
如果catch放在后面，抛异常的步骤到catch前的步骤不执行，catch后的步骤继续执行
var begin = Date.now();

doStep1()
.then( () => {
	var end = Date.now();
	console.log(`完成第一步 (${end-begin}毫秒)`)
	return doStep2()
} )
.then( () => {
	var end = Date.now();
	console.log(`完成第二步 (${end-begin}毫秒)`)
	return doStep3()
}  )
.catch( () => {
	var end = Date.now();
	console.log(`异常！！！ (${end-begin}毫秒)`)
})
.then( () => {
	var end = Date.now();
	console.log(`结束 (${ end-begin } 毫秒)`)
});


function doStep1(){
	return new Promise( (resolve, reject) => {
		console.log('执行第一步')
		throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
function doStep2(){
	return new Promise( (resolve, reject) => {
		console.log('执行第二步')
		// throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
function doStep3(){
	return new Promise( (resolve, reject) => {
		console.log('执行第三步')
		// throw new Error('网络异常')
		setTimeout(resolve, 1000)
	})
}
		</pre>
	</div>
	<div class="aShow" id="showResult4">
		
	</div>
</div>
<script>
$(function(){
	var begin = Date.now();

	doStep1()
	.then( () => {
		var end = Date.now();
		show(`完成第一步 (${end-begin}毫秒)`)
		return doStep2()
	} )
	.then( () => {
		var end = Date.now();
		show(`完成第二步 (${end-begin}毫秒)`)
		return doStep3()
	}  )
	.catch( () => {
		var end = Date.now();
		show(`异常！！！ (${end-begin}毫秒)`)
	})
	.then( () => {
		var end = Date.now();
		show(`结束 (${ end-begin } 毫秒)`)
	});
	

	function doStep1(){
		return new Promise( (resolve, reject) => {
			show('执行第一步')
			throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}
	function doStep2(){
		return new Promise( (resolve, reject) => {
			show('执行第二步')
			// throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}
	function doStep3(){
		return new Promise( (resolve, reject) => {
			show('执行第三步')
			// throw new Error('网络异常')
			setTimeout(resolve, 1000)
		})
	}


	function show(str){
		$('<p>'+str+'</p>').appendTo('#showResult4');
	}
})
</script>


<div class="aTitle">Promise.all() 【ES6】</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
Promise.all 是当所有给定的可迭代完成时执行 resolve，或者任何  promises 失败时执行 reject。
（所有任务并行执行）

Promise.all([promise1, promise2, ...])
<b>参数：</b>
promiseArray promise实例组成的数组

<b>脚本:</b>
var begin = Date.now();

var work1 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		console.log(`完成第1步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work2 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		console.log(`完成第2步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work3 = new Promise( (resolve, reject) => {
	//setTimeout(resolve, 1000)
	setTimeout( () => {
		console.log(`完成第3步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})

Promise.all([work1, work2, work3])
	.then( () => {
		var end = Date.now();
		console.log(`执行结束，耗时${end-begin}ms`)
	})
		</pre>
	</div>
	<div class="aShow" id="showResult5">
		
	</div>
</div>	
<script>
$(function(){

var begin = Date.now();

var work1 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		show(`完成第1步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work2 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		show(`完成第2步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work3 = new Promise( (resolve, reject) => {
	//setTimeout(resolve, 1000)
	setTimeout( () => {
		show(`完成第3步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})

Promise.all([work1, work2, work3])
	.then( () => {
		var end = Date.now();
		show(`执行结束，耗时${end-begin}ms`)
	})

function show(str){
	$('<p>'+str+'</p>').appendTo('#showResult5');
}
})
</script>


<div class="aTitle">Promise.race() 竞争【ES6】</div>
<div class="aPane">
	<div class="aCode">
		<pre class="note">
Promise.race 方法返回一个新的 promise，参数iterable中只要有一个promise对象"完成（resolve）"
或"失败（reject）"，新的promise就会立刻"完成（resolve）"或者"失败（reject）"，并获得之前那个
promise对象的返回值或者错误原因。

Promise.race([promise1, promise2, ...])
<b>参数：</b>
promiseArray promise实例组成的数组

<b>脚本:</b>
var begin = Date.now();

var work1 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		console.log(`完成第1步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work2 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		console.log(`完成第2步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 2000)
})
var work3 = new Promise( (resolve, reject) => {
	//setTimeout(resolve, 1000)
	setTimeout( () => {
		console.log(`完成第3步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 3000)
})

Promise.race([work1, work2, work3])
	.then( () => {
		var end = Date.now();
		console.log(`race执行结束，耗时${end-begin}ms`)
	})
})
		</pre>
	</div>
	<div class="aShow" id="showResult6">
		
	</div>
</div>	
<script>
$(function(){	
var begin = Date.now();

var work1 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		show(`完成第1步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 1000)
})
var work2 = new Promise( (resolve, reject) => {
	setTimeout( () => {
		show(`完成第2步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 2000)
})
var work3 = new Promise( (resolve, reject) => {
	//setTimeout(resolve, 1000)
	setTimeout( () => {
		show(`完成第3步，耗时${Date.now()-begin}ms`)
		resolve()
	}, 3000)
})

Promise.race([work1, work2, work3])
	.then( () => {
		var end = Date.now();
		show(`race执行结束，耗时${end-begin}ms`)
	})
})
function show(str){
	$('<p>'+str+'</p>').appendTo('#showResult6');
}
</script>
</body>
</html>